package edu.neu.madcourse.dharabhavsar.utils.firebaseconn;

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.Query;
import com.firebase.client.ValueEventListener;

import java.util.HashMap;
import java.util.Random;

import edu.neu.madcourse.dharabhavsar.model.communication.GameData;
import edu.neu.madcourse.dharabhavsar.model.communication.UserData;

/**
 * Created by derylrodrigues on 3/4/16.
 */
public class RemoteClient {

    private static final String MyPREFERENCES = "MyPrefs" ;
    public static final String USER_UNIQUE_KEY = "user_key";
    public static final String GAME_UNIQUE_KEY = "game_key";
    public static final String USER_DATA = "userData";
//    private static final String FIREBASE_DB = "https://<Your FireBase AppName>.firebaseIO.com/";
    private static final String FIREBASE_DB = "https://popping-fire-5271.firebaseio.com/";
    private static final String TAG = "RemoteClient";
    private static boolean isDataChanged = false;
    private Context mContext;
    private HashMap<String, String> fireBaseData = new HashMap<String, String>();
    SharedPreferences prefs;
    private UserData user = new UserData();
    private HashMap<String, UserData> fireBaseUserData = new HashMap<String, UserData>();
    private HashMap<String, UserData> fireBaseRandomUserData = new HashMap<String, UserData>();
    private static boolean isRandomDataChanged = false;

    public RemoteClient(Context mContext)
    {
        this.mContext = mContext;
        Firebase.setAndroidContext(mContext);
//        Firebase.getDefaultConfig().setLogLevel(Logger.Level.DEBUG);
        prefs = mContext.getSharedPreferences(RemoteClient.class.getSimpleName(), Context.MODE_PRIVATE);
    }


    public void saveValue(String key, String value) {
        Firebase ref = new Firebase(FIREBASE_DB);
        Firebase usersRef = ref.child(key);
        usersRef.setValue(value, new Firebase.CompletionListener() {
            @Override
            public void onComplete(FirebaseError firebaseError, Firebase firebase) {
                if (firebaseError != null) {
                    Log.d(TAG, "Data could not be saved. " + firebaseError.getMessage());
                } else {
                    Log.d(TAG, "Data saved successfully.");
                }
            }
        });
    }

    public boolean isDataFetched()
    {
        return isDataChanged;
    }

    public boolean isRandomDataFetched()
    {
        return isRandomDataChanged;
    }

    public String getValue(String key)
    {
        return fireBaseData.get(key);
    }

    public void fetchValue(String key) {

        Log.d(TAG, "Get Value for Key - " + key);
        Firebase ref = new Firebase(FIREBASE_DB + key);
        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                // snapshot contains the key and value
                isDataChanged = true;
                if (snapshot.getValue() != null) {
                    Log.d(TAG, "Data Received" + snapshot.getValue().toString());
                    // Adding the data to the HashMap
                    fireBaseData.put(snapshot.getKey(), snapshot.getValue().toString());
                } else {
                    Log.d(TAG, "Data Not Received");
                    fireBaseData.put(snapshot.getKey(), null);
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }

//    code to save and retrieve userData
    public void saveUserData(UserData value) {
        Firebase ref = new Firebase(FIREBASE_DB);
        Firebase usersRef = ref.child(USER_DATA);
        Firebase newUserRef = usersRef.push();
        newUserRef.setValue(value, new Firebase.CompletionListener() {
            @Override
            public void onComplete(FirebaseError firebaseError, Firebase firebase) {
                if (firebaseError != null) {
                    Log.d(TAG, "Data could not be saved. " + firebaseError.getMessage());
                } else {
                    Log.d(TAG, "Data saved successfully.");
                }
            }
        });
        // Get the unique ID generated by push() - adding it to SharedPrefrences
        String uniqueUserId = newUserRef.getKey();
        Log.e(TAG, "uniqueUserId = " + uniqueUserId);
        SharedPreferences.Editor editor = prefs.edit();
        editor.putString(USER_UNIQUE_KEY, uniqueUserId);
        editor.commit();
        String userKey = prefs.getString(USER_UNIQUE_KEY, "");
        Log.e(TAG, "in prefs, userKey = " + userKey);
    }

    public void fetchUserData(String key, final String userId) {
        Log.e(TAG, "Get Value for Key - " + userId);
        Firebase ref = new Firebase(FIREBASE_DB);
//        Firebase ref = new Firebase(FIREBASE_DB + key);
        Firebase usersRef = ref.child(key);
        Query queryRef = usersRef.orderByKey();
//        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                isDataChanged = true;
                // snapshot contains the key and value
                if (snapshot.getValue() != null) {
                    Log.e(TAG, "There are " + snapshot.getChildrenCount() + " users");
                    // Adding the data to the HashMap
                    for (DataSnapshot postSnapshot : snapshot.getChildren()) {
                        if (postSnapshot.getKey().equals(userId)) {
                            user = postSnapshot.getValue(UserData.class);
                            Log.e(TAG, user.getUserId() + " - " + user.getUserName()
                                    + " - " + user.getUserCombineBestScore() + " - " + user.getUserIndividualBestScore());
                            fireBaseUserData.put(userId, user);
                        }
                    }
                } else {
                    Log.e(TAG, "Data Not Received");
                    fireBaseUserData.put(userId, null);
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }

    public UserData getUserData(String userId) {
        return (fireBaseUserData.get(userId));
    }

//    code to store gameData
    public void saveGameData(GameData value) {
//        TODO saving game data for both the plays
        Firebase ref = new Firebase(FIREBASE_DB);
        Firebase gameRef = ref.child("gameData");
        Firebase newGameRef = gameRef.push();
        newGameRef.setValue(value, new Firebase.CompletionListener() {
            @Override
            public void onComplete(FirebaseError firebaseError, Firebase firebase) {
                if (firebaseError != null) {
                    Log.d(TAG, "Data could not be saved. " + firebaseError.getMessage());
                } else {
                    Log.d(TAG, "Data saved successfully.");
                }
            }
        });
        // Get the unique ID generated by push() - adding it to SharedPrefrences
        String uniqueGameKey = newGameRef.getKey();
        Log.e(TAG, "uniqueGameKey = " + uniqueGameKey);
        SharedPreferences.Editor editor = prefs.edit();
        editor.putString(GAME_UNIQUE_KEY, uniqueGameKey);
        editor.commit();
        String gameKey = prefs.getString(GAME_UNIQUE_KEY, "");
        Log.e(TAG, "in prefs, gameKey = " + gameKey);
    }

    public void fetchGameData(String key, final String userId) {
//        TODO game data fetching for async play + combine play
        Log.d(TAG, "Get Value for Key - " + key);
        Firebase ref = new Firebase(FIREBASE_DB + key);
        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                // snapshot contains the key and value
                if (snapshot.getValue() != null) {
                    Log.d(TAG, "There are " + snapshot.getChildrenCount() + " blog posts");
                    // Adding the data to the HashMap
                    for (DataSnapshot postSnapshot : snapshot.getChildren()) {
                        if (postSnapshot.getKey().equals(userId)) {
                            UserData user = postSnapshot.getValue(UserData.class);
                            Log.e(TAG, user.getUserId() + " - " + user.getUserName()
                                    + " - " + user.getUserCombineBestScore() + " - " + user.getUserIndividualBestScore());
                        }
                    }
                } else {
                    Log.d(TAG, "Data Not Received");
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }

    public void fetchRandomUsers(final String key, final String userId) {
//        TODO users for 2player combat game
        Log.d(TAG, "Get Value for Key - " + key);
        Firebase ref = new Firebase(FIREBASE_DB + key);
        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                isRandomDataChanged = true;
                // snapshot contains the key and value
                if (snapshot.getValue() != null) {
                    Log.d(TAG, "There are " + snapshot.getChildrenCount() + " blog posts");
                    // Adding the data to the HashMap
                    for (DataSnapshot postSnapshot : snapshot.getChildren()) {
                        if (!postSnapshot.getKey().equals(userId)) {
                            UserData user = postSnapshot.getValue(UserData.class);
                            if(!user.isChallengedGamePending()) {
                                fireBaseRandomUserData.put(userId, user);
                                Log.e(TAG, user.getUserId() + " - " + user.getUserName()
                                        + " - " + user.getUserCombineBestScore() + " - " + user.getUserIndividualBestScore()
                                        + " - " + user.getChallengedBy() + " - " + user.getTeamPlayerName()
                                        + " - " + user.isCombineGameRequest() + " - " + user.isChallengedGamePending());
                            }
                        }
                    }
                } else {
                    Log.d(TAG, "Data Not Received");
                    fireBaseRandomUserData.put(userId, null);
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }

    public UserData getRandomUserData() {
        Random generator = new Random();
        Object[] values = fireBaseRandomUserData.values().toArray();
        Object randomValue = values[generator.nextInt(values.length)];
        return (UserData)randomValue;
    }

    public void fetchAllUsers(String key, final String userId) {
//        TODO users for combine play
        Log.d(TAG, "Get Value for Key - " + key);
        Firebase ref = new Firebase(FIREBASE_DB + key);
        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                // snapshot contains the key and value
                if (snapshot.getValue() != null) {
                    Log.d(TAG, "There are " + snapshot.getChildrenCount() + " blog posts");
                    // Adding the data to the HashMap
                    for (DataSnapshot postSnapshot : snapshot.getChildren()) {
                        if (postSnapshot.getKey().equals(userId)) {
                            UserData user = postSnapshot.getValue(UserData.class);
                            Log.e(TAG, user.getUserId() + " - " + user.getUserName()
                                    + " - " + user.getUserCombineBestScore() + " - " + user.getUserIndividualBestScore());
                        }
                    }
                } else {
                    Log.d(TAG, "Data Not Received");
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }

    public void fetchScoreBoardData(String key, final String userId) {
//        TODO score board data
        Log.d(TAG, "Get Value for Key - " + key);
        Firebase ref = new Firebase(FIREBASE_DB + key);
        Query queryRef = ref.orderByKey();
        queryRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                // snapshot contains the key and value
                if (snapshot.getValue() != null) {
                    Log.d(TAG, "There are " + snapshot.getChildrenCount() + " blog posts");
                    // Adding the data to the HashMap
                    for (DataSnapshot postSnapshot : snapshot.getChildren()) {
                        if (postSnapshot.getKey().equals(userId)) {
                            UserData user = postSnapshot.getValue(UserData.class);
                            Log.e(TAG, user.getUserId() + " - " + user.getUserName()
                                    + " - " + user.getUserCombineBestScore() + " - " + user.getUserIndividualBestScore());
                        }
                    }
                } else {
                    Log.d(TAG, "Data Not Received");
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                Log.e(TAG, firebaseError.getMessage());
                Log.e(TAG, firebaseError.getDetails());
            }
        });
    }
}
